version: 2.1

orbs:
  cloudsmith-npm: ft-circleci-orbs/cloudsmith-npm@1.0
  coveralls: coveralls/coveralls@1.0.6

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:22.15

all_branches_filter: &all_branches_filter
  filters:
    tags:
      only:
        - /^v[0-9]+\.[0-9]+\.[0-9]+/
        - /staging-.*/
    branches:
      only: /.*/

publish_with_tags_filter: &publish_with_tags_filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only:
        - /^v[0-9]+\.[0-9]+\.[0-9]+$/
        - /^v[0-9]+\.[0-9]+\.[0-9]+\-rc[0-9]+$/
commands:
  install-dependencies:
    steps:
      - cloudsmith-npm/configure_npm:
          repository: financial-times-internal-releases
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci --ignore-scripts
            else
              echo "package.json and package-lock.json unchanged, using cached node_modules"
            fi
jobs:
  coveralls_report:
    <<: *defaults
    steps:
      - checkout
      - install-dependencies

  get_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - install-dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish --access=public

workflows:
  build_and_publish:
    jobs:
      - get_dependencies:
          <<: *all_branches_filter
          context: professional

      - build:
          <<: *all_branches_filter
          requires:
            - get_dependencies

      - lint:
          <<: *all_branches_filter
          requires:
            - build

      - coveralls_report:
          <<: *all_branches_filter
          context: professional
          requires:
            - build

      - publish:
          <<: *publish_with_tags_filter
          context:
            - npm-publish-token
          requires:
            - build
            - lint
            - coveralls_report